### ISSUE TITLE
Any pretrained checkpoints?

### ISSUE THREAD

**Issue by voodoohop** [goel-shashank/CyCLIP#1]

**Comment by goel-shashank** [comment]
You can find them [here](https://drive.google.com/drive/u/0/folders/1K0kPJZ3MA4KAdx3Fpq25dgW59wIf7M-x).

**Comment by bdevnani3** [comment]
Is the `3M` checkpoint the best one available? I'm wondering if I'm missing the 12M checkpoint.

**Comment by Hritikbansal** [comment]
Table 1 of the paper uses [this](https://drive.google.com/drive/folders/1RWXNQ6sJjGSAyVr-0XXZ5FZOCss63jO6?usp=sharing) checkpoint (trained with CC3M data only ~ 2.6M datapoints). CyCLIP-3M checkpoint is used for Figure 4 (trained on 3M datapoints from CC3M and remaining from CC12M). 

Unfortunately, we didn't have the resources (compute, bandwidth) to run a CC12M version of our model at the time of the project. We shall if we can train a CC12M version and will keep a look out for other repos that intend to replicate large scale CLIP models such as https://github.com/LAION-AI/CLIP_benchmark

**Comment by bdevnani3** [comment]
Sounds good - thanks for closing the loop so promptly!
