### ISSUE TITLE
Run Command used for Experiments

### ISSUE THREAD

**Issue by gstoica27** [goel-shashank/CyCLIP#2]
Hi, 

Thanks for all this cool research and making making your code public! 

I was hoping to explore this area a bit and wanted to train a CyCLIP model from scratch on the CC3M dataset like was described in the paper. I was wondering if by chance there was an example run command used to e.g. generate the base CyCLIP model? I know that you describe the setup in the preprint - I just want to make sure I am running the correct command. 

Thanks very much!

**Comment by goel-shashank** [comment]
Hi Georgia, thanks for your feedback. The readme is still a work in progress and should be completed within a few days. I will keep this issue open for now. Stay tuned!

**Comment by gstoica27** [comment]
Hey, I hope everything is well. 

I was just wondering if there was any update on this at all? Don't mean to rush or anything, we're just really interested in trying this model for our research.

Thanks! 
George

**Comment by Hritikbansal** [comment]
Hi George! 
This command should work:

`python -m main --name exp1 --train_data <path to train csv file> --validation_data <path to valid csv file>
--image_key <column name of the image paths in the train/validation csv file> --caption_key <column name of the captions
in the train/validation csv file> --device_ids "0,1,2" --distributed --cylambda1 0.5 --cylambda2 0.5 `

Your train/validation csv/tsv file should have 2 columns containing captions and the path to corresponding images on the machine. this script does not download the images for the captions directly. To download the images from their URL for CC3M and/or CC12M, use our `utils/download.py` script.

If this helps you in getting started then please close this issue. 

P.S. The authors are working during summers at different locations, so we have not had time to update the repo for some time. We shall add more descriptions to it as soon as we get time.

**Comment by gstoica27** [comment]
No worries! And thank you!
