### ISSUE TITLE
Creating embedding for own image and text

### ISSUE THREAD

**Issue by nikky4D** [goel-shashank/CyCLIP#3]
is there an inference script I can use to get embeddings for my own text and image?

**Comment by Hritikbansal** [comment]
We shall release a working notebook soon where we exemplify it, thanks for the request nikky! Meanwhile, if you figure it out through our code, you can load the checkpoints directly from [here](https://drive.google.com/drive/u/0/folders/1K0kPJZ3MA4KAdx3Fpq25dgW59wIf7M-x).

**Comment by lbc402** [comment]
Waiting for the inference script... Is there an approximate release date?

**Comment by Hritikbansal** [comment]
We are sorry for the delay. Both the authors are busy on different projects over the summer. We will try to release an inference script this month itself. Thank you for your patience.

**Comment by Hritikbansal** [comment]
Hi @lbc402 @nikky4D , apologies for the delay! But the example inference script is out for CyCLIP - https://github.com/goel-shashank/CyCLIP/blob/main/CyCLIP_Example.ipynb
